---
- name: add default user to the user groups docker and sudo
  user:
    name: "{{ user }}"
    groups: sudo,docker
    state: present

- name: Ensures app dir exists
  file:
    path: "{{ app_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Adding nginx file
  template:
    src: ../templates/nginx.conf.j2
    dest: "{{ app_dir }}/nginx.conf"
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Adding .env file
  template:
    src: ../templates/.env.j2
    dest: "{{ app_dir }}/.env"
    owner: "{{ user }}"
    group: "{{ group }}"
